# main paths
data_path: "SIIM-ACR-Pneumothorax-Segmentation"
annotation_path: "SIIM-ACR-Pneumothorax-Segmentation"

# annotation paths
annotations: "test.csv"
images: "dicom-images"
masks: "masks"

# exp params
save_path: "Experiments/SIIM-ACR-Pneumothorax-Segmentation/baseline"
test_name: test

trainer:
  precision: '16-mixed'
  accelerator: auto
  #  accelerator: gpu
  devices: auto
  #  devices: [0]

weights: "Experiments/SIIM-ACR-Pneumothorax-Segmentation/baseline/model.ckpt"
model:
  smp_model_name: "Unet++"
  kwargs:
    encoder_name: 'tu-tf_efficientnet_b1'
    encoder_weights: 'imagenet'
    in_channels: 3
    classes: 1

dataloader:
  batch_size: 128
  num_workers: 2

preprocess:
  side_size: 512
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

transforms:
